### ISSUE TITLE
Install section of README should point to docs

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius-docs#6]
Need to remove the inline install section and point over to [Installation and Support](http://docs.ortelius.io/userguide/installation-and-support/)

**Comment by divya-mohan0209** [comment]
@sbtaylor15 : Could you please guide where this change needs to be made?

**Comment by sbtaylor15** [comment]
@divya-mohan0209 its the section starting with **Ortelius as a SaaS option** up to **Support** in the https://github.com/ortelius/ortelius [README](https://github.com/ortelius/ortelius/blob/master/README.md).  @jiakalita maybe working on this.  (Its hard to assign things since not everyone is a member of the project but an external contributor)

**Comment by TracyRagan** [comment]
Fixed
